/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alodiga.wallet.common.enumeraciones;

/**
 *
 * @author jose
 */
public enum ResponseCodeE {

    SUCCESS("00"),
    INVALID_DATA("01"),
    EXPIRED_PASSWORD("03"),
    NO_TRUST_IP("04"),
    INVALID_CREDENTIALS("05"),
    BLOCKED_USER("06"),
    INVALID_VALIDATION_CODE("07"),
    PHONE_NUMBER_ALREADY_EXISTS("08"),
    SEND_MAIL_FAILED("09"),
    EMAIL_ALREADY_EXISTS("10"),
    NULL_DATA("11"),
    FIRST_LOGIN("12"),
    EIN_ALREADY_EXISTS("14"),
    FEDERAL_TAX_ALREADY_EXISTS("15"),
    BANK_ACCOUNT_ALREADY_EXISTS("17"),
    GENERATE_CODE("18"),
    EXPIRED_TOKEN("19"),
    CARD_REQUEST_ACTIVATE("20"),
    MAX_AFFILIATIONS_REACH("21"),
    USER_NOT_HAS_PHONE_NUMBER("22"),
    USER_NOT_HAS_PRODUCT("23"),
    TRANSACTION_LIST_NOT_FOUND_EXCEPTION("24"),
    EMPTY_LIST_HAS_BANK("25"),
    EMPTY_LIST_COUNTRY("26"),
    BALANCE_HISTORY_NOT_FOUND_EXCEPTION("27"),
    CONNECT_TIMEOUT_EXCEPTION("250"),
    SOCKECT_TIMEOUT_EXCEPTION("251"),
    EMPTY_LIST_HAS_CARD("28"),
    USER_NOT_HAS_CARD("29"),
    DOES_NOT_HAVE_AN_ASSOCIATED_COMPANION_CARD("30"),
    APPLICATION_DOESNT_EXISTS("94"),
    SUSPECT_USER("95"),
    PENDING_USER("96"),
    USER_NO_EXISTS("97"),
    ERROR_CREDENTIALS("98"),
    INTERNAL_ERROR("99"),
    USER_NOT_HAS_BANK("197"),
    ACCOUNT_NUMBER_ALREADY_EXIST("198"),
    
    //Mensajeria TopUp
    DENOMINATION_NOT_AVAILABLE("301"),
    DESTINATION_MSISDN_OUT_OF_RANGE("101"),
    DESTINATION_NOT_PREPAID("204"),
    ERROR_TRANSACTION_TOP_UP("205"),
    
    //Mensajes Guardar Transaction
    TRANSACTION_AMOUNT_LIMIT("30"),
    TRANSACTION_MAX_NUMBER_BY_ACCOUNT("31"),
    TRANSACTION_MAX_NUMBER_BY_CUSTOMER("32"),
    USER_HAS_NOT_BALANCE("33"),
    TRANSACTION_AMOUNT_LIMIT_DIALY("34"),
    TRANSACTION_AMOUNT_LIMIT_MONTHLY("35"),
    TRANSACTION_AMOUNT_LIMIT_YEARLY("36"),
    TRANSACTION_QUANTITY_LIMIT_DIALY("37"),
    TRANSACTION_QUANTITY_LIMIT_MONTHLY("38"),
    TRANSACTION_QUANTITY_LIMIT_YEARLY("39"),
    DISABLED_TRANSACTION("41"),
    
    //Mensajes Status Cumplimient
    NOT_VALIDATE("40"),
    
    //Mensajes Status Card
    CARD_NUMBER_EXISTS("50"),
    NOT_ALLOWED_TO_CHANGE_STATE("51"),
    THERE_IS_NO_SEARCH_RECORD("52"),
    NON_EXISTENT_ACCOUNT("53"),
    AUTHENTICATE_IMPOSSIBLE("54"),
    SERVICE_NOT_ALLOWED("55"),
    OPERATION_NOT_ALLOWED_FOR_THIS_SERVICE("56"),
    UNABLE_TO_ACCESS_DATA("57"),
    THERE_ARE_NO_RECORDS_FOR_THE_REQUESTED_SEARCH("58"),
    THE_REQUESTED_PRODUCT_DOES_NOT_EXIST("59"),
    THE_NUMBER_OF_ORDERS_ALLOWED_IS_EXCEEDED("60"),
    BUSINESS_NOT_HAS_PRODUCT("61"),
    EXISTING_WALLET_BUSINESS("62"),
    
    //Mensajes transferencia cardtocard credencial servicio autorizacion
    NON_EXISTENT_CARD("100"),
    EXPIRATION_DATE_DIFFERS("102"),
    EXPIRED_CARD("103"),
    LOCKED_CARD("104"),
    BLOCKED_ACCOUNT("105"),
    INVALID_ACCOUNT("106"),
    INSUFFICIENT_BALANCE("107"),
    INSUFFICIENT_LIMIT("108"),
    CREDIT_LIMIT_0("109"),
    CREDIT_LIMIT_0_OF_THE_DESTINATION_ACCOUNT("110"),
    ERROR_PROCESSING_THE_TRANSACTION("111"),
    INVALID_TRANSACTION("112"),
    ERROR_VALIDATION_THE_TERMINAL("113"),
    DESTINATION_CARD_LOCKED("114"),
    DESTINATION_ACCOUNT_LOCKED("115"),
    INVALID_DESTINATION_CARD("116"),
    INVALID_DESTINATION_ACCOUNT("117"),
    THE_AMOUNT_MUST_BE_POSITIVE_AND_THE_AMOUNT_IS_REPORTED("118"),
    THE_AMOUNT_MUST_BE_NEGATIVE_AND_THE_AMOUNT_IS_REPORTED("119"),
    INVALID_TRANSACTION_DATE("120"),
    INVALID_TRANSACTION_TIME("121"),
    SOURCE_OR_DESTINATION_ACCOUNT_IS_NOT_COMPATIBLE_WITH_THIS_OPERATION_NN("122"),
    SOURCE_OR_DESTINATION_ACCOUNT_IS_NOT_COMPATIBLE_WITH_THIS_OPERATION_SN("123"),
    SOURCE_OR_DESTINATION_ACCOUNT_IS_NOT_COMPATIBLE_WITH_THIS_OPERATION_NS("124"),
    TRASACTION_BETWEEN_ACCOUNTS_NOT_ALLOWED("125"),
    TRADE_VALIDATON_ERROR("126"),
    DESTINATION_CARD_DOES_NOT_SUPPORT_TRANSACTION("127"),
    OPERATION_NOT_ENABLED_FOR_THE_DESTINATION_CARD("128"),
    BIN_NOT_ALLOWED("129"),
    STOCK_CARD("130"),
    THE_ACCOUNT_EXCEEDS_THE_MONTHLY_LIMIT("131"),
    THE_PAN_FIELD_IS_MANDATORY("132"),
    THE_AMOUNT_TO_BE_RECHARGE_IS_INCORRECT("133"),
    THE_AMOUNT_MUST_BE_GREATER_THAN_0("134"),
    TRANSACTION_ANSWERED("135"),
    SUCCESSFUL_RECHARGE("136"),
    ERROR_VALIDATING_PIN("137"),
    ERROR_VALIDATING_CVC1("138"),
    ERROR_VALIDATING_CVC2("139"),
    PIN_CHANGE_ERROR("140"),
    ERROR_VALIDATING_THE_ITEM("141"),
    INVALID_AMOUNT("142"),
    NOT_ACCOUNT_BANK_ASOCIATE("304"),
    
    //MENSAJES AFINITAS
    CALL_ISSUER("150"),
    NOT_AUTHORIZED("151"),
    INVALID_TRADE("152"),
    RETAIN_CARD("153"),
    INVALID_TRANSACTION_AFINITAS("154"),
    RETRY_AFINITAS("155"),
    TRANSACTION_NOT_PERMITTED("156"),
    INVALID_CARD("157"),
    FORMAT_ERROR("158"),
    INSUFFICIENT_FUNDS("159"),
    EXPIRED_CARD_AFINITAS("160"),
    INVALID_PIN("161"),
    DEFERRED_PAYMENT_NOT_PERMITTED("162"),
    LIMIT_EXCEEDED("163"),
    TYPE_OF_PLAN_TERM_INVALID("164"),
    DUPLICATED_TRANSACTION("165"),
    EXCESSED_AUTHORIZATIONS("166"),
    CP_NOT_PERMITTED_BY_TH("167"),
    TERMINAL_ERROR("168"),
    UNACTIVATED_CARD("169"),
    INVALID_COIN("170"),
    CHIP_READING_ERROR("171"),
    INVALID_CHIP("172"),
    CHIP_NOT_SUPPORTED("173"),
    UNKNOWN("174"),
    THE_DEVICE_IS_NOT_ACTIVE("175"),
    THE_BRANCH_IS_NOT_ACTIVE("176"),
    TRADE_IS_NOT_ACTIVE("177"),
    THE_REQUEST_IS_EMPTY("178"),
    MISSING_PARAMETER_ON_REQUEST("179"),
    RESOURCE_NOT_FOUND("180"),
    ANSWER_EMPTY("181"),
    THE_TRANSACTION_EXCEEDS_THE_PERMITTED_AMOUNT("182"),
    TRANSACTION_EXCEEDS_THE_ALLOWED_DAILY_AMOUNT("183"),
    TRANSACTION_EXCEEDS_THE_MONTHLY_AMOUNT_ALLOWED("184"),
    NON_ACTIVE_PROMOTIONS("185"),
    PROMOTION_NOT_ACTIVE("186"),
    THE_TRANSACTION_IS_NOT_WITHIN_THE_PERMITTED_SCHEDULE("187"),
    THE_TRANSACTION_DOES_NOT_EXIST("188"),
    TRANSACTION_WITH_NOT_APPROVED_SOURCE("189"),
    INVALID_MEMBERSHIP("190"),
    TRANSACTION_CANCELED_PREVIOUSLY("191"),
    PREVIOUSLY_REVERSED_TRANSACTION("192"),
    EXCEED_PERMITTED_DAILY_TRANSACTIONS("193"),
    THE_CORPORATE_IS_NOT_ACTIVE("194"),
    ANSWER_NOT_FOUND("195"),
    TIME_EXCEEDED_TO_PERFORM_CANCELLATION("196"),
    CREDENTIALS_WS_INAVAILABLE("143"),
    THE_SERVICE_NOT_AVAILABLE("144"),
    
    //MENSAJE METODO DE PAGO
    NOT_ASSOCIATED_PAYMENT_INFO("220"),
    
    //Mensajes de portalWeb
    NOT_PERSON_TYPE("300"),
    NOT_DOCUMENTS_PERSON_TYPE("301"),
    NOT_COLLECTION_TYPE("302"),
    NOT_COLLECTION_REQUEST("303");

    private final String code;

    private ResponseCodeE(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

}

